title: Avtomat Docs
description: A simple, yet powerful, automation tool for cloud engineers.
theme: just-the-docs

url: https://avtomat-hub.github.io
logo: /assets/images/logo.png
favicon_ico: /assets/images/favicon.png

aux_links:
  "avtomat.io":
    - "//avtomat.io"

callouts_level: quiet # or loud
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  danger:
    title: Danger
    color: red

collections:
  aws:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    aws:
      name: Amazon Web Services