title: Avtomat Docs
description: A simple, yet powerful, automation tool for AWS engineers.
theme: just-the-docs

url: https://avtomat-hub.github.io

callouts_level: quiet # or loud
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  danger:
    title: Danger
    color: red